name = input("Who are you? ")
want = input("What is something that you want? ")
worry = input("Tell me something you worry about. ")
first = int(input("What is one of your favourite numbers between 1 and 10? "))
second = int(input("Now how about another? "))
know = input("What is something you understand? ")
feel = input("How are you feeling right now? ")
dream = input("What did you dream about recently? ")
print(f"I am {name}.")
print(f"Something I want is {want}.")
print(worry,"is something I worry about.")
print(first * second,"is my lucky number.")
print(f"A thing I understand is {know}.")
print(f"Today I have been feeling {feel}.")
print(f"I had a dream about {dream} recently.")